In [1]:
import numpy as np

In [2]:
a = np.array([6,7,8,9])

In [3]:
a[0:2]

array([6, 7])

In [4]:
a[2:]

array([8, 9])

In [5]:
a[-1]

9

In [6]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [7]:
b[1,2]

6

In [8]:
b[2,0]

7

In [10]:
b[-1, 0:2]    #gives last row and its first two elements 

array([7, 8])

In [11]:
mon_sales = np.array([30,33,35,28,42])
result = mon_sales < 32
result

array([ True, False, False,  True, False])

In [12]:
mon_sales[result]

array([30, 28])

In [15]:
index = np.argmax(mon_sales)
index    # index of the maximum element in the mon_sales

4

In [17]:
b[:,2]  #give me all rows but only with 2nd column

array([3, 6, 9])